include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    prefer_double_quotes: true
    prefer_relative_imports: true
    always_declare_return_types: true
    eol_at_end_of_file: true
    use_super_parameters: true